FROM ubuntu:22.04

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y \
    build-essential \
    cmake \
    libgtest-dev \
    libbenchmark-dev \
    libboost-all-dev \
    python3 \
    git
